# Generated by Django 4.1.7 on 2023-03-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('your_movies', '0007_userinfo_alter_movie_user_id_alter_review_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movie',
            name='unique_movie_for_user',
        ),
    ]
